name: 'LeanCloud Self Wake'

 # 触发条件
on:
  watch:
    types: [started]
  schedule:
    - cron: '*/25 23-23 * * ?'    # 北京时间 07:00 - 07:59，每 25 分钟触发一次
    - cron: '*/25 0-15 * * ?'     # 北京时间 08:00 - 23:59，每 25 分钟触发一次

jobs:
  visit-my-site:
     runs-on: ubuntu-latest
     steps:
       - name: 'visit my site'
         env:
           MY_SITE: ${{ secrets.LEADCLOUDSITE }}
         # 向站点发送 GET 请求
         run:
           curl $MY_SITE
